# Generated by Django 2.0 on 2021-07-23 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materials',
            old_name='Material_Id',
            new_name='id',
        ),
    ]
