# Generated by Django 2.0 on 2021-07-23 07:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210723_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
